name: combinact
channels:
- defaults
- conda-forge
dependencies:
- certifi>=2016.2.28
- openssl>=1.0.2l
- pip>=9.0.1
- python~=3.6.2
- readline>=6.2
- setuptools>=36.4.0
- sqlite~=3.13.0
- tk>=8.5.18
- wheel>=0.29.0
- xz>=5.2.3
- zlib>=1.2.11
- pip:
  - cycler==0.10.0
  - dataclasses==0.8
  - future==0.18.2
  - joblib==0.17.0
  - kiwisolver==1.3.0
  - matplotlib==3.3.2
  - numpy==1.19.5
  - packaging==20.4
  - pillow==8.3.1
  - pyparsing==2.4.7
  - python-dateutil==2.8.1
  - scikit-learn==0.23.2
  - scipy==1.5.2
  - six==1.14.0
  - sklearn==0.0
  - threadpoolctl==2.1.0
  - torch==1.9.0
  - torch-lr-finder==0.2.1
  - torchaudio==0.9.0
  - torchvision==0.10.0
  - tqdm==4.51.0
  - typing-extensions==3.10.0.0
