import numpy as np


def nn_mnist_p1(rng):
    return {
        "combinact": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                      "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                      "adam_eps": np.exp(rng.uniform(-22, -15)),
                      "adam_wd": np.exp(rng.uniform(-15, -8)),
                      "max_lr": np.exp(rng.uniform(-8, -2)),
                      "cycle_peak": rng.uniform(0.1, 0.5)
                      },
        "bin_partition_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "bin_partition_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                                 "max_lr": np.exp(rng.uniform(-8, -2)),
                                 "cycle_peak": rng.uniform(0.1, 0.5)
                                 },
        "bin_all_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                         "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                         "adam_eps": np.exp(rng.uniform(-22, -15)),
                         "adam_wd": np.exp(rng.uniform(-15, -8)),
                         "max_lr": np.exp(rng.uniform(-8, -2)),
                         "cycle_peak": rng.uniform(0.1, 0.5)
                         },
        "bin_all_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "bin_all_nopass_sgm": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "prod": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "lae": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                "adam_eps": np.exp(rng.uniform(-22, -15)),
                "adam_wd": np.exp(rng.uniform(-15, -8)),
                "max_lr": np.exp(rng.uniform(-8, -2)),
                "cycle_peak": rng.uniform(0.1, 0.5)
                },
        "signed_geomean": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "linf": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "max": {
            "adam_beta_1": np.exp(rng.uniform(-1.57, -1.04)),
            "adam_beta_2": np.exp(rng.uniform(-5.94, -4.75)),
            "adam_eps": np.exp(rng.uniform(-17.44, -15.46)),
            "adam_wd": np.exp(rng.uniform(-11.44, -7.73)),
            "max_lr": np.exp(rng.uniform(-6.07, -5.27)),
            "cycle_peak": rng.uniform(0.31, 0.44),
        },
        "relu": {
            "adam_beta_1": np.exp(rng.uniform(-1.82, -1.46)),
            "adam_beta_2": np.exp(rng.uniform(-7.89, -6.17)),
            "adam_eps": np.exp(rng.uniform(-18.31, -16.96)),
            "adam_wd": np.exp(rng.uniform(-11.2, -8.41)),
            "max_lr": np.exp(rng.uniform(-6.17, -5.64)),
            "cycle_peak": rng.uniform(0.39, 0.5),
        },
        "swishk": {
            "adam_beta_1": np.exp(rng.uniform(-2.06, -1.23)),
            "adam_beta_2": np.exp(rng.uniform(-7.96, -4.73)),
            "adam_eps": np.exp(rng.uniform(-18.75, -15.84)),
            "adam_wd": np.exp(rng.uniform(-12.43, -10.35)),
            "max_lr": np.exp(rng.uniform(-6.96, -5.59)),
            "cycle_peak": rng.uniform(0.2, 0.4),
        },
        "l2": {
            "adam_beta_1": np.exp(rng.uniform(-4.41, -1.09)),
            "adam_beta_2": np.exp(rng.uniform(-4.89, -4.55)),
            "adam_eps": np.exp(rng.uniform(-21.91, -19.36)),
            "adam_wd": np.exp(rng.uniform(-12.67, -11.17)),
            "max_lr": np.exp(rng.uniform(-5.77, -4.53)),
            "cycle_peak": rng.uniform(0.3, 0.37),
        },

    }


def cnn_cifar10_p1(rng):
    return {

        "combinact": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                      "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                      "adam_eps": np.exp(rng.uniform(-22, -15)),
                      "adam_wd": np.exp(rng.uniform(-15, -8)),
                      "max_lr": np.exp(rng.uniform(-8, -2)),
                      "cycle_peak": rng.uniform(0.1, 0.5)
                      },
        "bin_partition_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "bin_partition_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                                 "max_lr": np.exp(rng.uniform(-8, -2)),
                                 "cycle_peak": rng.uniform(0.1, 0.5)
                                 },
        "bin_all_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                         "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                         "adam_eps": np.exp(rng.uniform(-22, -15)),
                         "adam_wd": np.exp(rng.uniform(-15, -8)),
                         "max_lr": np.exp(rng.uniform(-8, -2)),
                         "cycle_peak": rng.uniform(0.1, 0.5)
                         },
        "bin_all_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "bin_all_nopass_sgm": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "prod": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "lae": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                "adam_eps": np.exp(rng.uniform(-22, -15)),
                "adam_wd": np.exp(rng.uniform(-15, -8)),
                "max_lr": np.exp(rng.uniform(-8, -2)),
                "cycle_peak": rng.uniform(0.1, 0.5)
                },
        "signed_geomean": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "linf": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "max": {
            "adam_beta_1": np.exp(rng.uniform(-2.36, -1.47)),
            "adam_beta_2": np.exp(rng.uniform(-5.05, -3.56)),
            "adam_eps": np.exp(rng.uniform(-17.56, -14.67)),
            "adam_wd": np.exp(rng.uniform(-9.92, -7.32)),
            "max_lr": np.exp(rng.uniform(-5.32, -4.66)),
            "cycle_peak": rng.uniform(0.24, 0.52),
        },
        "relu": {
            "adam_beta_1": np.exp(rng.uniform(-1.85, -1.3)),
            "adam_beta_2": np.exp(rng.uniform(-7.53, -5.46)),
            "adam_eps": np.exp(rng.uniform(-20.86, -16.18)),
            "adam_wd": np.exp(rng.uniform(-10.75, -7.57)),
            "max_lr": np.exp(rng.uniform(-6.88, -6.69)),
            "cycle_peak": rng.uniform(0.3, 0.49),
        },
        "swishk": {
            "adam_beta_1": np.exp(rng.uniform(-1.38, -1.06)),
            "adam_beta_2": np.exp(rng.uniform(-6.72, -4.85)),
            "adam_eps": np.exp(rng.uniform(-20.11, -17.62)),
            "adam_wd": np.exp(rng.uniform(-15.24, -10.63)),
            "max_lr": np.exp(rng.uniform(-5.72, -5.36)),
            "cycle_peak": rng.uniform(0.26, 0.41),
        },
        "l2": {
            "adam_beta_1": np.exp(rng.uniform(-2.55, -1.74)),
            "adam_beta_2": np.exp(rng.uniform(-7.59, -4.79)),
            "adam_eps": np.exp(rng.uniform(-21.25, -15.03)),
            "adam_wd": np.exp(rng.uniform(-11.88, -8.35)),
            "max_lr": np.exp(rng.uniform(-6.25, -5.87)),
            "cycle_peak": rng.uniform(0.27, 0.43),
        },
    }


def nn_mnist_p3(rng):
    return {
        "combinact": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                      "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                      "adam_eps": np.exp(rng.uniform(-22, -15)),
                      "adam_wd": np.exp(rng.uniform(-15, -8)),
                      "max_lr": np.exp(rng.uniform(-8, -2)),
                      "cycle_peak": rng.uniform(0.1, 0.5)
                      },
        "bin_partition_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "bin_partition_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                                 "max_lr": np.exp(rng.uniform(-8, -2)),
                                 "cycle_peak": rng.uniform(0.1, 0.5)
                                 },
        "bin_all_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                         "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                         "adam_eps": np.exp(rng.uniform(-22, -15)),
                         "adam_wd": np.exp(rng.uniform(-15, -8)),
                         "max_lr": np.exp(rng.uniform(-8, -2)),
                         "cycle_peak": rng.uniform(0.1, 0.5)
                         },
        "bin_all_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "bin_all_nopass_sgm": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "prod": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "lae": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                "adam_eps": np.exp(rng.uniform(-22, -15)),
                "adam_wd": np.exp(rng.uniform(-15, -8)),
                "max_lr": np.exp(rng.uniform(-8, -2)),
                "cycle_peak": rng.uniform(0.1, 0.5)
                },
        "signed_geomean": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "linf": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "max": {
            "adam_beta_1": np.exp(rng.uniform(-3.69, -2.51)),
            "adam_beta_2": np.exp(rng.uniform(-6.3, -4.89)),
            "adam_eps": np.exp(rng.uniform(-21.09, -16.33)),
            "adam_wd": np.exp(rng.uniform(-14.42, -11.75)),
            "max_lr": np.exp(rng.uniform(-7.15, -4.88)),
            "cycle_peak": rng.uniform(0.29, 0.42),
        },
        "relu": {
            "adam_beta_1": np.exp(rng.uniform(-3.04, -1.94)),
            "adam_beta_2": np.exp(rng.uniform(-10.49, -4.47)),
            "adam_eps": np.exp(rng.uniform(-21.52, -17.01)),
            "adam_wd": np.exp(rng.uniform(-11.12, -10.39)),
            "max_lr": np.exp(rng.uniform(-6.89, -6.4)),
            "cycle_peak": rng.uniform(0.24, 0.31),
        },
        "swishk": {
            "adam_beta_1": np.exp(rng.uniform(-0.61, -0.1)),
            "adam_beta_2": np.exp(rng.uniform(-6.99, -4.36)),
            "adam_eps": np.exp(rng.uniform(-20.48, -17.2)),
            "adam_wd": np.exp(rng.uniform(-10.98, -8.29)),
            "max_lr": np.exp(rng.uniform(-7.18, -5.52)),
            "cycle_peak": rng.uniform(0.1, 0.41),
        },
        "l2": {
            "adam_beta_1": np.exp(rng.uniform(-1.81, -1.07)),
            "adam_beta_2": np.exp(rng.uniform(-6.61, -6.23)),
            "adam_eps": np.exp(rng.uniform(-17.5, -16.43)),
            "adam_wd": np.exp(rng.uniform(-13.09, -10.01)),
            "max_lr": np.exp(rng.uniform(-5.7, -4.94)),
            "cycle_peak": rng.uniform(0.22, 0.46),
        },
    }


def cnn_cifar10_p3(rng):
    return {
        "combinact": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                      "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                      "adam_eps": np.exp(rng.uniform(-22, -15)),
                      "adam_wd": np.exp(rng.uniform(-15, -8)),
                      "max_lr": np.exp(rng.uniform(-8, -2)),
                      "cycle_peak": rng.uniform(0.1, 0.5)
                      },
        "bin_partition_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "bin_partition_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                                 "max_lr": np.exp(rng.uniform(-8, -2)),
                                 "cycle_peak": rng.uniform(0.1, 0.5)
                                 },
        "bin_all_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                         "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                         "adam_eps": np.exp(rng.uniform(-22, -15)),
                         "adam_wd": np.exp(rng.uniform(-15, -8)),
                         "max_lr": np.exp(rng.uniform(-8, -2)),
                         "cycle_peak": rng.uniform(0.1, 0.5)
                         },
        "bin_all_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "bin_all_nopass_sgm": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "prod": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "lae": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                "adam_eps": np.exp(rng.uniform(-22, -15)),
                "adam_wd": np.exp(rng.uniform(-15, -8)),
                "max_lr": np.exp(rng.uniform(-8, -2)),
                "cycle_peak": rng.uniform(0.1, 0.5)
                },
        "signed_geomean": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "linf": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "max": {
            "adam_beta_1": np.exp(rng.uniform(-3.79, -2.43)),
            "adam_beta_2": np.exp(rng.uniform(-6.06, -4.0)),
            "adam_eps": np.exp(rng.uniform(-21.12, -17.44)),
            "adam_wd": np.exp(rng.uniform(-11.55, -6.82)),
            "max_lr": np.exp(rng.uniform(-5.74, -5.63)),
            "cycle_peak": rng.uniform(0.38, 0.48),
        },
        "relu": {
            "adam_beta_1": np.exp(rng.uniform(-2.8, -1.75)),
            "adam_beta_2": np.exp(rng.uniform(-8.2, -4.37)),
            "adam_eps": np.exp(rng.uniform(-19.31, -16.07)),
            "adam_wd": np.exp(rng.uniform(-9.52, -7.18)),
            "max_lr": np.exp(rng.uniform(-7.5, -6.82)),
            "cycle_peak": rng.uniform(0.2, 0.3),
        },
        "swishk": {
            "adam_beta_1": np.exp(rng.uniform(-1.14, -0.63)),
            "adam_beta_2": np.exp(rng.uniform(-6.27, -3.29)),
            "adam_eps": np.exp(rng.uniform(-19.14, -15.8)),
            "adam_wd": np.exp(rng.uniform(-13.77, -12.21)),
            "max_lr": np.exp(rng.uniform(-6.3, -6.08)),
            "cycle_peak": rng.uniform(0.33, 0.43),
        },
        "l2": {
            "adam_beta_1": np.exp(rng.uniform(-2.81, -1.73)),
            "adam_beta_2": np.exp(rng.uniform(-6.73, -5.89)),
            "adam_eps": np.exp(rng.uniform(-22.16, -17.3)),
            "adam_wd": np.exp(rng.uniform(-14.55, -10.64)),
            "max_lr": np.exp(rng.uniform(-6.68, -6.01)),
            "cycle_peak": rng.uniform(0.26, 0.43),
        },
    }
