import numpy as np


def nn_mnist_p1(rng):
    return {
        "combinact": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                      "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                      "adam_eps": np.exp(rng.uniform(-22, -15)),
                      "adam_wd": np.exp(rng.uniform(-15, -8)),
                      "max_lr": np.exp(rng.uniform(-8, -2)),
                      "cycle_peak": rng.uniform(0.1, 0.5)
                      },
        "bin_partition_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "bin_partition_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                                 "max_lr": np.exp(rng.uniform(-8, -2)),
                                 "cycle_peak": rng.uniform(0.1, 0.5)
                                 },
        "bin_all_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                         "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                         "adam_eps": np.exp(rng.uniform(-22, -15)),
                         "adam_wd": np.exp(rng.uniform(-15, -8)),
                         "max_lr": np.exp(rng.uniform(-8, -2)),
                         "cycle_peak": rng.uniform(0.1, 0.5)
                         },
        "bin_all_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "bin_all_nopass_sgm": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "prod": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "lae": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                "adam_eps": np.exp(rng.uniform(-22, -15)),
                "adam_wd": np.exp(rng.uniform(-15, -8)),
                "max_lr": np.exp(rng.uniform(-8, -2)),
                "cycle_peak": rng.uniform(0.1, 0.5)
                },
        "signed_geomean": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "linf": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "max": {
            "adam_beta_1": np.exp(rng.uniform(-1.44, -1.18)),
            "adam_beta_2": np.exp(rng.uniform(-5.43, -4.89)),
            "adam_eps": np.exp(rng.uniform(-17.26, -15.13)),
            "adam_wd": np.exp(rng.uniform(-11.79, -8.93)),
            "max_lr": np.exp(rng.uniform(-5.81, -5.3)),
            "cycle_peak": rng.uniform(0.35, 0.44),
        },
        "relu": {
            "adam_beta_1": np.exp(rng.uniform(-1.78, -1.51)),
            "adam_beta_2": np.exp(rng.uniform(-7.74, -6.31)),
            "adam_eps": np.exp(rng.uniform(-18.0, -16.92)),
            "adam_wd": np.exp(rng.uniform(-10.73, -8.96)),
            "max_lr": np.exp(rng.uniform(-6.01, -5.63)),
            "cycle_peak": rng.uniform(0.39, 0.46),
        },
        "swishk": {
            "adam_beta_1": np.exp(rng.uniform(-1.68, -1.26)),
            "adam_beta_2": np.exp(rng.uniform(-7.6, -4.17)),
            "adam_eps": np.exp(rng.uniform(-18.73, -16.84)),
            "adam_wd": np.exp(rng.uniform(-11.84, -10.33)),
            "max_lr": np.exp(rng.uniform(-6.29, -5.72)),
            "cycle_peak": rng.uniform(0.18, 0.43),
        },
        "l2": {
            "adam_beta_1": np.exp(rng.uniform(-3.66, -1.12)),
            "adam_beta_2": np.exp(rng.uniform(-4.87, -4.61)),
            "adam_eps": np.exp(rng.uniform(-21.51, -20.16)),
            "adam_wd": np.exp(rng.uniform(-12.42, -11.31)),
            "max_lr": np.exp(rng.uniform(-5.69, -4.69)),
            "cycle_peak": rng.uniform(0.31, 0.36),
        },

    }


def cnn_cifar10_p1(rng):
    return {

        "combinact": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                      "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                      "adam_eps": np.exp(rng.uniform(-22, -15)),
                      "adam_wd": np.exp(rng.uniform(-15, -8)),
                      "max_lr": np.exp(rng.uniform(-8, -2)),
                      "cycle_peak": rng.uniform(0.1, 0.5)
                      },
        "bin_partition_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "bin_partition_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                                 "max_lr": np.exp(rng.uniform(-8, -2)),
                                 "cycle_peak": rng.uniform(0.1, 0.5)
                                 },
        "bin_all_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                         "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                         "adam_eps": np.exp(rng.uniform(-22, -15)),
                         "adam_wd": np.exp(rng.uniform(-15, -8)),
                         "max_lr": np.exp(rng.uniform(-8, -2)),
                         "cycle_peak": rng.uniform(0.1, 0.5)
                         },
        "bin_all_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "bin_all_nopass_sgm": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "prod": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "lae": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                "adam_eps": np.exp(rng.uniform(-22, -15)),
                "adam_wd": np.exp(rng.uniform(-15, -8)),
                "max_lr": np.exp(rng.uniform(-8, -2)),
                "cycle_peak": rng.uniform(0.1, 0.5)
                },
        "signed_geomean": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "linf": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "max": {
            "adam_beta_1": np.exp(rng.uniform(-2.16, -1.41)),
            "adam_beta_2": np.exp(rng.uniform(-4.63, -3.87)),
            "adam_eps": np.exp(rng.uniform(-17.43, -15.47)),
            "adam_wd": np.exp(rng.uniform(-8.27, -7.26)),
            "max_lr": np.exp(rng.uniform(-5.32, -4.99)),
            "cycle_peak": rng.uniform(0.24, 0.46),
        },
        "relu": {
            "adam_beta_1": np.exp(rng.uniform(-1.61, -1.22)),
            "adam_beta_2": np.exp(rng.uniform(-7.83, -5.39)),
            "adam_eps": np.exp(rng.uniform(-19.42, -16.4)),
            "adam_wd": np.exp(rng.uniform(-9.3, -8.04)),
            "max_lr": np.exp(rng.uniform(-6.84, -6.72)),
            "cycle_peak": rng.uniform(0.3, 0.44),
        },
        "swishk": {
            "adam_beta_1": np.exp(rng.uniform(-1.37, -1.12)),
            "adam_beta_2": np.exp(rng.uniform(-6.22, -5.05)),
            "adam_eps": np.exp(rng.uniform(-19.45, -17.92)),
            "adam_wd": np.exp(rng.uniform(-14.3, -11.59)),
            "max_lr": np.exp(rng.uniform(-5.63, -5.44)),
            "cycle_peak": rng.uniform(0.33, 0.39),
        },
        "l2": {
            "adam_beta_1": np.exp(rng.uniform(-2.2, -1.8)),
            "adam_beta_2": np.exp(rng.uniform(-7.12, -5.27)),
            "adam_eps": np.exp(rng.uniform(-21.53, -16.99)),
            "adam_wd": np.exp(rng.uniform(-12.46, -10.11)),
            "max_lr": np.exp(rng.uniform(-6.07, -5.93)),
            "cycle_peak": rng.uniform(0.3, 0.41),
        },
    }


def nn_mnist_p3(rng):
    return {
        "combinact": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                      "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                      "adam_eps": np.exp(rng.uniform(-22, -15)),
                      "adam_wd": np.exp(rng.uniform(-15, -8)),
                      "max_lr": np.exp(rng.uniform(-8, -2)),
                      "cycle_peak": rng.uniform(0.1, 0.5)
                      },
        "bin_partition_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "bin_partition_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                                 "max_lr": np.exp(rng.uniform(-8, -2)),
                                 "cycle_peak": rng.uniform(0.1, 0.5)
                                 },
        "bin_all_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                         "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                         "adam_eps": np.exp(rng.uniform(-22, -15)),
                         "adam_wd": np.exp(rng.uniform(-15, -8)),
                         "max_lr": np.exp(rng.uniform(-8, -2)),
                         "cycle_peak": rng.uniform(0.1, 0.5)
                         },
        "bin_all_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "bin_all_nopass_sgm": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "prod": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "lae": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                "adam_eps": np.exp(rng.uniform(-22, -15)),
                "adam_wd": np.exp(rng.uniform(-15, -8)),
                "max_lr": np.exp(rng.uniform(-8, -2)),
                "cycle_peak": rng.uniform(0.1, 0.5)
                },
        "signed_geomean": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "linf": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "max": {
            "adam_beta_1": np.exp(rng.uniform(-3.29, -2.62)),
            "adam_beta_2": np.exp(rng.uniform(-5.18, -4.83)),
            "adam_eps": np.exp(rng.uniform(-20.57, -16.11)),
            "adam_wd": np.exp(rng.uniform(-14.82, -12.26)),
            "max_lr": np.exp(rng.uniform(-6.2, -4.88)),
            "cycle_peak": rng.uniform(0.28, 0.37),
        },
        "relu": {
            "adam_beta_1": np.exp(rng.uniform(-2.92, -2.1)),
            "adam_beta_2": np.exp(rng.uniform(-10.93, -4.3)),
            "adam_eps": np.exp(rng.uniform(-19.23, -16.75)),
            "adam_wd": np.exp(rng.uniform(-10.95, -10.43)),
            "max_lr": np.exp(rng.uniform(-6.82, -6.55)),
            "cycle_peak": rng.uniform(0.25, 0.27),
        },
        "swishk": {
            "adam_beta_1": np.exp(rng.uniform(-0.25, -0.07)),
            "adam_beta_2": np.exp(rng.uniform(-5.45, -4.38)),
            "adam_eps": np.exp(rng.uniform(-19.6, -18.44)),
            "adam_wd": np.exp(rng.uniform(-10.33, -8.68)),
            "max_lr": np.exp(rng.uniform(-6.58, -6.02)),
            "cycle_peak": rng.uniform(0.07, 0.4),
        },
        "l2": {
            "adam_beta_1": np.exp(rng.uniform(-1.85, -1.38)),
            "adam_beta_2": np.exp(rng.uniform(-6.52, -6.38)),
            "adam_eps": np.exp(rng.uniform(-17.61, -16.67)),
            "adam_wd": np.exp(rng.uniform(-12.85, -9.88)),
            "max_lr": np.exp(rng.uniform(-5.63, -4.98)),
            "cycle_peak": rng.uniform(0.27, 0.47),
        },
    }


def cnn_cifar10_p3(rng):
    return {
        "combinact": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                      "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                      "adam_eps": np.exp(rng.uniform(-22, -15)),
                      "adam_wd": np.exp(rng.uniform(-15, -8)),
                      "max_lr": np.exp(rng.uniform(-8, -2)),
                      "cycle_peak": rng.uniform(0.1, 0.5)
                      },
        "bin_partition_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "bin_partition_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                                 "max_lr": np.exp(rng.uniform(-8, -2)),
                                 "cycle_peak": rng.uniform(0.1, 0.5)
                                 },
        "bin_all_full": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                         "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                         "adam_eps": np.exp(rng.uniform(-22, -15)),
                         "adam_wd": np.exp(rng.uniform(-15, -8)),
                         "max_lr": np.exp(rng.uniform(-8, -2)),
                         "cycle_peak": rng.uniform(0.1, 0.5)
                         },
        "bin_all_nopass": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "bin_all_nopass_sgm": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                               "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                               "adam_eps": np.exp(rng.uniform(-22, -15)),
                               "adam_wd": np.exp(rng.uniform(-15, -8)),
                               "max_lr": np.exp(rng.uniform(-8, -2)),
                               "cycle_peak": rng.uniform(0.1, 0.5)
                               },
        "prod": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "lae": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                "adam_eps": np.exp(rng.uniform(-22, -15)),
                "adam_wd": np.exp(rng.uniform(-15, -8)),
                "max_lr": np.exp(rng.uniform(-8, -2)),
                "cycle_peak": rng.uniform(0.1, 0.5)
                },
        "signed_geomean": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                           "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                           "adam_eps": np.exp(rng.uniform(-22, -15)),
                           "adam_wd": np.exp(rng.uniform(-15, -8)),
                           "max_lr": np.exp(rng.uniform(-8, -2)),
                           "cycle_peak": rng.uniform(0.1, 0.5)
                           },
        "linf": {"adam_beta_1": np.exp(rng.uniform(-5, 0)),
                 "adam_beta_2": np.exp(rng.uniform(-12, -4)),
                 "adam_eps": np.exp(rng.uniform(-22, -15)),
                 "adam_wd": np.exp(rng.uniform(-15, -8)),
                 "max_lr": np.exp(rng.uniform(-8, -2)),
                 "cycle_peak": rng.uniform(0.1, 0.5)
                 },
        "max": {
            "adam_beta_1": np.exp(rng.uniform(-2.82, -2.58)),
            "adam_beta_2": np.exp(rng.uniform(-5.76, -3.68)),
            "adam_eps": np.exp(rng.uniform(-21.41, -17.38)),
            "adam_wd": np.exp(rng.uniform(-10.23, -5.52)),
            "max_lr": np.exp(rng.uniform(-5.75, -5.63)),
            "cycle_peak": rng.uniform(0.41, 0.48),
        },
        "relu": {
            "adam_beta_1": np.exp(rng.uniform(-2.08, -1.81)),
            "adam_beta_2": np.exp(rng.uniform(-7.27, -5.33)),
            "adam_eps": np.exp(rng.uniform(-17.41, -16.94)),
            "adam_wd": np.exp(rng.uniform(-9.12, -7.01)),
            "max_lr": np.exp(rng.uniform(-7.4, -7.24)),
            "cycle_peak": rng.uniform(0.25, 0.31),
        },
        "swishk": {
            "adam_beta_1": np.exp(rng.uniform(-1.2, -0.57)),
            "adam_beta_2": np.exp(rng.uniform(-5.07, -3.48)),
            "adam_eps": np.exp(rng.uniform(-18.8, -16.35)),
            "adam_wd": np.exp(rng.uniform(-13.74, -12.42)),
            "max_lr": np.exp(rng.uniform(-6.25, -6.12)),
            "cycle_peak": rng.uniform(0.32, 0.4),
        },
        "l2": {
            "adam_beta_1": np.exp(rng.uniform(-2.25, -1.86)),
            "adam_beta_2": np.exp(rng.uniform(-6.61, -6.09)),
            "adam_eps": np.exp(rng.uniform(-21.03, -18.32)),
            "adam_wd": np.exp(rng.uniform(-15.38, -12.26)),
            "max_lr": np.exp(rng.uniform(-6.36, -6.0)),
            "cycle_peak": rng.uniform(0.26, 0.42),
        },
    }
